package Routes{

class RouterFactory {
    Factory to create Router
    --props--
        userType: number
}

Index ..> Router

Router ..> RouterFactory

RouterFactory ..>UniversityRoutes
RouterFactory ..>AdminRoutes
RouterFactory ..>TeacherRoutes
RouterFactory ..>StudentRoutes
RouterFactory ..>PublicRoutes

note top of RouterFactory
        React App from here!!
end note

class Router <<created by react-router>>{

}

class UniversityRoutes {
    --routes--
        + index -> UniversityIndex
        + academicyears -> UniversityAcademicYears
        + admins -> UniversityAdmins
}
/'
UniversityRoutes ..> UniversityPages
'/
UniversityRoutes ..> UniversityIndex
UniversityRoutes ..> UniversityAcademicYears
UniversityRoutes ..> UniversityAdmins

class AdminRoutes{
    --routes--
        + index -> AdminIndex
        + confirm/teacher -> AdminUsersNotConfirmed
        + confirm/students -> AdminUsersNotConfirmed
        + user/teacher -> AdminUserConfirmed
        + user/students -> AdminUserConfirmed
        + courses -> AdminCourses
        + courses/:examId -> AdminCourseExams
}
/'
AdminRoutes ..> AdminPages
'/
AdminRoutes ..> AdminIndex
AdminRoutes ..> AdminUsersConfirmed
AdminRoutes ..> AdminUsersNotConfirmed
AdminRoutes ..> AdminCourses
AdminRoutes ..> AdminCourseExams

class TeacherRoutes {
    --routes--
        + index -> TeacherIndex
        + exams -> TeacherExams
        + exams/:examid -> TeacherExamStudents
}
/'
TeacherRoutes ..> TeacherPages
'/
TeacherRoutes ..> TeacherIndex
TeacherRoutes ..> TeacherExams
TeacherRoutes ..> TeacherExamStudents

class StudentRoutes{
    --render--
         index -> StudentIndex
         other exams -> OptionalExams
}
/'
StudentRoutes ..> StudentPages
'/
StudentRoutes ..> StudentIndex
StudentRoutes ..> StudentExams
StudentRoutes ..> StudentOptionalExams
StudentRoutes ..> StudentSummary

class PublicRoutes{
    --routes--
        + index -> PublicIndex
        + help -> HelpPage
        + price -> PricePage
        + request -> SubmissionPage
}
/'
PublicRoutes ..> PublicPages
'/
PublicRoutes ..> PublicIndex
PublicRoutes ..> HelpPage
PublicRoutes ..> PricePage
PublicRoutes ..> SubmissionPage

}
