
package Routes{

class RoutesFactory{
	TODO - metodo per la creazione
}

class UniversityRoutes {
    --routes--
        + index -> UniversityIndex
        + academicyears -> UniversityAcademicYears
        + admins -> UniversityAdmins
}

class AdminRoutes{
    --routes--
        + index -> AdminIndex
        + confirm/teacher -> AdminUsersNotConfirmed
        + confirm/students -> AdminUsersNotConfirmed
        + user/teacher -> AdminUserConfirmed
        + user/students -> AdminUserConfirmed
        + courses -> AdminCourses
        + courses/:examId -> AdminCourseExams
}

class TeacherRoutes {
    --routes--
        + index -> TeacherIndex
        + exams -> TeacherExams
        + exams/:examid -> TeacherExamStudents
}

class StudentRoutes{
    --render--
         index -> StudentIndex
         other exams -> OptionalExams
	TODO - fixare
}

class PublicRoutes{
    --routes--
        + index -> PublicIndex
        + help -> HelpPage
        + price -> PricePage
        + request -> SubmissionPage
}

RoutesFactory --> UniversityRoutes
RoutesFactory --> AdminRoutes
RoutesFactory --> TeacherRoutes
RoutesFactory --> StudentRoutes
RoutesFactory --> PublicRoutes

UniversityRoutes ..> UniversityIndex
UniversityRoutes ..> UniversityAcademicYears
UniversityRoutes ..> UniversityAdmins

AdminRoutes ..> AdminIndex
AdminRoutes ..> AdminUsersConfirmed
AdminRoutes ..> AdminUsersNotConfirmed
AdminRoutes ..> AdminCourses
AdminRoutes ..> AdminCourseExams

TeacherRoutes ..> TeacherIndex
TeacherRoutes ..> TeacherExams
TeacherRoutes ..> TeacherExamStudents

StudentRoutes ..> StudentIndex
StudentRoutes ..> StudentExams
StudentRoutes ..> CreditsToEnd

PublicRoutes .> PublicIndex
PublicRoutes .> HelpPage
PublicRoutes .> PricePage
PublicRoutes .> SubmissionPage

}
