package Routes{

class RoutesFactory {
   {static} + createRoutes(userType: number): object
}

Page ..> Router

Router --> RoutesFactory

RoutesFactory ..>UniversityRoutes
RoutesFactory ..>AdminRoutes
RoutesFactory ..>TeacherRoutes
RoutesFactory ..>StudentRoutes
RoutesFactory ..>PublicRoutes

class Router <<created by react-router>>{

}

class UniversityRoutes {
    --routes--
        + index -> UniversityIndex
        + academicyears -> UniversityAcademicYears
        + admins -> UniversityAdmins
}
/'
UniversityRoutes ..> UniversityPages
'/
UniversityRoutes ..> UniversityIndex
UniversityRoutes ..> UniversityAcademicYears
UniversityRoutes ..> UniversityAdmins

class AdminRoutes{
    --routes--
        + index -> AdminIndex
        + confirm/teacher -> AdminUsersNotConfirmed
        + confirm/students -> AdminUsersNotConfirmed
        + user/teacher -> AdminUserConfirmed
        + user/students -> AdminUserConfirmed
        + courses -> AdminCourses
        + courses/:examId -> AdminCourseExams
}
/'
AdminRoutes ..> AdminPages
'/
AdminRoutes ..> AdminIndex
AdminRoutes ..> AdminUsersConfirmed
AdminRoutes ..> AdminUsersNotConfirmed
AdminRoutes ..> AdminCourses
AdminRoutes ..> AdminCourseExams

class TeacherRoutes {
    --routes--
        + index -> TeacherIndex
        + exams -> TeacherExams
        + exams/:examid -> TeacherExamStudents
}
/'
TeacherRoutes ..> TeacherPages
'/
TeacherRoutes ..> TeacherIndex
TeacherRoutes ..> TeacherExams
TeacherRoutes ..> TeacherExamStudents

class StudentRoutes{
    --render--
         index -> StudentIndex
         other exams -> OptionalExams
}
/'
StudentRoutes ..> StudentPages
'/
StudentRoutes ..> StudentIndex
StudentRoutes ..> StudentExams
StudentRoutes ..> StudentOptionalExams
StudentRoutes ..> StudentSummary

class PublicRoutes{
    --routes--
        + login -> LoginPage
        + logout -> LogoutPage
        + index -> PublicIndex
        + help -> HelpPage
        + price -> PricePage
        + request -> SubmissionPage
}
PublicRoutes ..> LoginPage
PublicRoutes ..> LogoutPage
PublicRoutes ..> PublicIndex
PublicRoutes ..> HelpPage
PublicRoutes ..> PricePage
PublicRoutes ..> SubmissionPage

}
