@startuml
skinparam classAttributeIconSize 0
class Course{
+ getExamNumber(contract: address): number
+ getExamContractAt(contract: address, number _index): address
+ getName(contract: address): number
+ getCreditsToGraduate(contract: address): number
+ getSolarYear(contract: address): number
+ addNewExam(contract: address, _name: number, _credits: number, _obbligatoriety: bool)
}
@enduml
