@startuml
skinparam classAttributeIconSize 0
class Exam{
+ getEnrolledNumber(contract: address): uint
+ getEnrolledContractAt(contract: address, _index:uint): address
+ getCourse(contract: address): address
+ getName(contract: address): bytes32
+ getTeacherContract(contract: address): address
+ getObbligatoriety(contract: address): bool
+ getCredits(contract: address): uint8
+ addMeAsSubscriber(contract: address)
}
@enduml
