@startuml
skinparam classAttributeIconSize 0
class Exam{
+ getEnrolledNumber(contract: address): number
+ getEnrolledContractAt(contract: address, _index:number): address
+ getCourse(contract: address): address
+ getName(contract: address): number
+ getTeacherContract(contract: address): address
+ getObligatoriness(contract: address): bool
+ getCredits(contract: address): number
+ addMeAsSubscriber(contract: address)
}
@enduml
