@startuml
skinparam classAttributeIconSize 0
class Student {
+ getCourseContract(contract: address): address
+ getExamNumber(contract: address): uint
+ getExamContractAt(contract: address, _index: uint): address
+ getExamSubscriptionAt(contract: address, _index: uint): bool
+ getExamValuationAt(contract: address, _index: uint): uint8
+ enrollToOptionalExam(contract: address, _index: uint)
+ getIndexOfExam(contract: address, exam: address): uint
}
@enduml
