@startuml
skinparam classAttributeIconSize 0
class Teacher {
+ getExamNumber(contract: address): number
+ getExamContractAt(contract: address, _index: number): address
+ registerNewVoteStudentExam(contract: address, _examindex: number, _student: number, _valuation: number)
}
@enduml
