@startuml
skinparam classAttributeIconSize 0
class UniversityTeacher{
+ getTeacherNumber(): number
+ getTeacherContractAddressAt(_index: number): address
+ getNonApprovedTeacherNumber(): number
+ getNotApprovedTeacherContractAddressAt(_index: number): address
+ getTeacherContractFromPublicAddress(_address: address): address
+ isTeacher(_address: address): bool
+ isNotConfirmedTeacher(_address: address): bool
+ getRoleByAddress(_address: address): number
+ requestTeacherAccount( _name: number, _surname: number)
+ confirmTeacher(_teacher: address)
+ denyTeacher(_teacher: address)
+ removeTeacher(_teacher: address)
}
@enduml
