@startuml
skinparam classAttributeIconSize 0
class UniversityAdmin {
+ isAdmin(_adminAddress: address): bool
+ getAdminNumber(): number
+ getAdminAt(_index: number): address
+ getRoleByAddress(_address: address): number
+ addNewAdmin(_adminAddress: address)
+ removeAdmin(_address: address)
}
@enduml
