@startuml
skinparam classAttributeIconSize 0
class UniversityYear {
+ getAcademicYearNumber(): uint
+ getAcademicYearContractAt(_index: uint): address
+ getAcademicYearContractByYear(_year:uint16): address
+ addNewAcademicYear(_year: uint16)
+ removeAcademicYear(_year: uint16)
}
@enduml
