@startuml
skinparam classAttributeIconSize 0
class UniversityContractSupplier << Singleton >> {
{static} - contractUniversityInstance: contract
__
{static} + getUniversityInstance(): object
}
@enduml

