@startuml
skinparam classAttributeIconSize 0
class UniversityContractSupplier << Singleton >> {
{static} - contractUniversityInstance: promise
__
{static} + getUniversityInstance(): object
}
@enduml

