@startuml
skinparam classAttributeIconSize 0
class UniversityYear {
+ getAcademicYearNumber(): number
+ getAcademicYearContractAt(_index: number): address
+ getAcademicYearContractByYear(_year:number): address
+ addNewAcademicYear(_year: number)
+ removeAcademicYear(_year: number)
}
@enduml
