@startuml
skinparam classAttributeIconSize 0
class UniversityStudent {
+ getStudentNumber(): number
+ getStudentContractAddressAt(_index: number): address
+ getNonApprovedStudentNumber(): number
+ getNotApprovedStudentContractAddressAt(_index: number): address
+ getStudentContractFromPublicAddress(_address: address): address
+ isStudent(_address: address): bool
+ isNotConfirmedStudent(_address: address): bool
+ getRoleByAddress(_address: address): number
+ requestStudentAccount(_name: number, _surname: number, _course: address)
+ confirmStudent(_student: address)
+ denyStudent(_student: address)
+ removeStudent(_student: address)
}
@enduml
