@startuml
!include UniversityStudent.iuml
!include UniversityTeacher.iuml
class UserData << facade >>{
  - getStudentData(): object
  - getTeacherData(): object
  + getData(number): object
}
UserData ..> UniversityStudent: <<use>>
UserData ..> UniversityTeacher: <<use>>
note right of UserData
  Facade for the login feature:
  SessionSaga is not aware of the different way
  to retrive student or teacher data
  in this way if in a future there will be
  necessary to specify admin's data we just have to
  add the instructions to the UserData facade.
  The SessionSaga will be more readable because the
  logic behind the contract selection (UniversityTeacher/UniversityStudent)
  is written in this facade
end note
