@startuml
skinparam classAttributeIconSize 0
class Year {
+ getCourseNumber(contract: address): number
+ getCourseContractAt(contract: address, _index: number): address
+ getSolarYear(contract: address): number
+ addNewCourse(contract: address, _name:number, _creditsForGraduation: number)
}
@enduml
