!include ../interfaces/saga.iuml
!include ../ducks/Admin.iuml

class AdminSaga {
    -- types --
    - GET_LISTS: string
    - GET_STUDENT_LIST: string
    - GET_TEACHERS_LIST: string
    - GET_PENDING_USERS_LIST: string
    - APPROVE_STUDENT: string
    - REMOVE_STUDENT: string
    - APPROVE_TEACHER: string
    - REMOVE_TEACHER: string
    -- sagas --
    - *getLists(action): void
    - *addUser(action): void
    - *removeUser(action): void
    -- actions --
    + getLists(): object
    + getStudentsListAction(): object
    + getTeachersListActiob(): object
    + getPendingUsersListAction(): object
    + approveUserAction(address = string): object
    + removeUserAction(address = string): object
    + approveTeacherAction(address = string): object
    + removeTeacherAction(address = string): object
}

AdminSaga --|> marvin.Saga
AdminSaga ..> marvin.Admin : <<use>>
