!include ../interfaces/saga.iuml
!include ../ducks/Admin.iuml

class AdminSaga {
    -- types --
    - GET_LISTS: string
    - GET_STUDENT_LIST: string
    - GET_TEACHERS_LIST: string
    - GET_PENDING_USERS_LIST: string
    - APPROVE_USER: string
    - REMOVE_USER: string
    -- sagas --
    - *getLists(): void
    - *getStudentList(): void
    - *getTeacherList(): void
    - *getPendingUsersList(): void
    - *addUser(action): void
    - *removeUser(action): void
    -- actions --
    + getLists(): object
    + getStudentsListAction(): object
    + getTeachersListActiob(): object
    + getPendingUsersListAction(): object
    + addUserAction(string): object
    + removeUserAction(string): object
}

AdminSaga --|> marvin.Saga
AdminSaga ..> marvin.Admin : <<use>>
