!include ../interfaces/saga.iuml
!include ../ducks/AdminEmployer.iuml
class AdminEmployerSaga{
  + handler(): void
  == types ==
  - ADD_NEW_ADMIN : string
  - REMOVE_ADMIN : string
  - GET_ALL_ADMINS : string
  == sagas ==
  - *addAdmin(action): void
  - *removeAdmin(action): void
  - *getAllAdmins(): void
  == actions ==
  + addNewAdminAction(string): object
  + removeAdminAction(string): object
  + getAllAdminsAction(): object
}
AdminEmployerSaga --|> marvin.Saga
AdminEmployerSaga ..> marvin.AdminEmployer : <<use>>
