!include ../interfaces/saga.iuml
!include ../ducks/Course.iuml
class CourseSaga{
  -- types --
  - ADD_NEW_DEGREE_COURSE : string
  - GET_ALL_DEGREE_COURSES : string
  - GET_ALL_YEARS : string
  -- sagas --
  - *addNewDegreeCourse(string, number) : void
  - *getAllDegreeCourses() : void
  - *getAllYears() : void
  -- actions --
  + addNewDegreeCourseAction(string, number) : object
  + getAllDegreeCoursesAction() : object
  + getAllYearsAction() : object
}
CourseSaga --|> marvin.Saga
CourseSaga ..> marvin.Course : <<use>>
