!include ../interfaces/saga.iuml
!include ../ducks/Evaluator.iuml
class EvaluatorSaga{
  -- types --
  - GET_LIST: string
  - ASSIGN_VOTE: string
  -- sagas --
  - *getStudentData(int = indexInExam)
  - *getList(string): void
  - *assignVote(int, int, int): void
  -- actions --
  + getListAction(examAddress = string): object
  + assignVoteAction(teacherAddress = string, examTeacherIndex = int, studentIndexInExams = int, vote = int): object
}
EvaluatorSaga --|> marvin.Saga
EvaluatorSaga ..> marvin.Evaluator: <<use>>
