!include ../interfaces/saga.iuml
!include ../ducks/Session.iuml
class SessionSaga{
  == types ==
  - LOGIN: string
  - UPDATE: string
  == sagas ==
  - *performLogin(): void
  - *retrieveData(): void
  == actions ==
  + loginAction(): object
  + updateData(): object
}
SessionSaga --|> marvin.Saga
SessionSaga ..> marvin.Session: <<use>>
SessionSaga ..> marvin.StudentSaga: <<use>>
