!include ../interfaces/saga.iuml
!include ../ducks/TeacherExams.iuml
class TeacherExamsSaga{
  -- types --
  - GET_LIST: string
  -- sagas --
  - *getList(): void
  -- actions --
  + getListAction(): object
}
TeacherExamsSaga --|> marvin.Saga
TeacherExamsSaga ..> marvin.TeacherExams: <<use>>
