!include ../interfaces/saga.iuml
!include ../ducks/UniversityAdmin.iuml
class UniversitySaga{
  + void handler()
  == types ==
  - ADD_NEW_ADMIN : string
  - REMOVE_ADMIN : string
  - GET_ADMIN_NUMBER : string
  - GET_ALL_ADMINS : string
  == sagas ==
  + void addAdmin(action)
  + void removeAdmin(action)
  + void getAllAdmins()
  + void adminNumber()
  == actions ==
  + object addNewAdminAction(string)
  + object removeAdminAction(string)
  + object getAdminNumberAction()
  + object getAllAdminsAction()
}
UniversitySaga --|> marvin.Saga
UniversitySaga ..> marvin.UniversityAdmin : <<use>>
