@startuml

    !include Contracts/Course.iuml
    !include Contracts/Exam.iuml
    !include Contracts/Student.iuml
    !include Contracts/Teacher.iuml
    !include Contracts/University.iuml
    !include Contracts/UniversityExam.iuml
    !include Contracts/UniversityStudent.iuml
    !include Contracts/UniversityTeacher.iuml
    !include Contracts/UniversityYear.iuml
    !include Contracts/UniversityAdmin.iuml
    !include Contracts/User.iuml
    !include Contracts/Year.iuml

Teacher --|> User
Student --|> User

UniversityAdmin --|> University
UniversityTeacher --|> UniversityAdmin
UniversityStudent --|> UniversityTeacher
UniversityYear --|> UniversityStudent
UniversityExam --|> UniversityYear

UniversityYear *-- Year
Year *-- Course
Course *-- Exam
UniversityExam --> Exam
UniversityExam --> Teacher
UniversityTeacher *-- Teacher
note on link: confirmed
UniversityTeacher *-- Teacher
note on link: unconfirmed
UniversityStudent *-- Student
note on link: confirmed
UniversityStudent *-- Student
note on link: unconfirmed

@enduml
