@startuml
skinparam classAttributeIconSize 0
    !include Contracts/Course.iuml
    !include Contracts/Exam.iuml
    !include Contracts/User.iuml
    !include Contracts/Student.iuml
    !include Contracts/Teacher.iuml
package "UniversityHierarchy" #DDDDDD {
    !include Contracts/University.iuml
    !include Contracts/UniversityExam.iuml
    !include Contracts/UniversityStudent.iuml
    !include Contracts/UniversityTeacher.iuml
    !include Contracts/UniversityYear.iuml
    !include Contracts/UniversityAdmin.iuml
}
    !include Contracts/Year.iuml

Teacher -u-|> User
Student -u-|> User

UniversityAdmin -u-|> University
UniversityTeacher -u-|> UniversityAdmin
UniversityStudent -u-|> UniversityTeacher
UniversityYear -u-|> UniversityStudent
UniversityExam -u-|> UniversityYear

UniversityYear *-- Year
Year *-- Course
Course *-- Exam
UniversityExam --> Exam
UniversityExam --> Teacher
UniversityTeacher *-r- Teacher
note on link: confirmed
UniversityTeacher *-r- Teacher
note on link: unconfirmed
UniversityStudent *-r- Student
note on link: confirmed
UniversityStudent *-r- Student
note on link: unconfirmed

@enduml
