!include ../interfaces/duck.iuml

class Admin{
  + object reducer(object, object)
  + ROLES: enum
  - initialState : object
  ==types==
  - SET_STUDENTS_LIST: string
  - SET_TEACHERS_LIST: string
  - SET_PENDING_LIST: string
  ==actions==
  + setStudentsList(array<Object>): object
  + setTeachersList(array<Object>): object
  + setPendingList(array<Object>): object
}

note right of Admin
initialState: {
  errored: false,
  loading: true,
  role: 2,
  lists: {
    StudentsList: array<Object> = []
    TeachersList: array<Object> = []
    PendingList: array<Object> = []
  }
}
end note
Admin --|>marvin.Duck
