!include ../interfaces/duck.iuml
class AdminEmployer{
  - initialState : object
  + ROLES: enum
  + reducer(object, object): object
  == types ==
  - SET_ADMINS_LIST : string
  - POP_ADMIN : string
  - PUSH_ADMIN : string
  == actions ==
  + setAdminList(array<Object>): object
  + pushAdmin(string): object
  + popAdmin(string): object
}
note right of University
initialState = {
 loading: false,
 errored: false,
 adminAccounts: array<string> = []
}
end note
AdminEmployer--|> marvin.Duck
