!include ../interfaces/duck.iuml
class Course{
  -- types --
  - PUSH_NEW_COURSE: string
  - SET_DEGREE_LIST : string
  - SET_ACADEMIC_YEARS_LIST : string
  - LIST_LOADING: string
  - LIST_ERRORED: string
  -- selectors --
  + degreeCourseBySign()
  + degreeCourseByAcademicYear()
  -- actions --
  + pushNewCourse(string): object
  + setDegreeList(array<Object>): object
  + setAllExamsList(array<Object>): object
  + setAcademicYearsList(array<Object>): object
  + listIsLoading(): object
  + listHasErrored(): object
}

note right of Course
initialState = {
  loading: false,
  errored: false,
  degreeCoursesList: array<{courseAddress, name, solarYear}> = [],
  academicYears: array<{solarYear}> = []
  }
end note

Course --|> marvin.Duck
