!include ../interfaces/duck.iuml
class ExamsList {
  == types ==
  - SET_LIST: string
  - SET_PROFESSOR: string
  - LIST_LOADING: string
  - LIST_ERRORED: string
  == actions ==
  + setList(): object
  + associateProfessorToExam(examAddress = string, professor = {name, surname, address})
  + listIsLoading(): object
  + listHasErrored(): object
}
note right of ExamsList
initialState = {
  loading: false,
  errored: false,
  list: array<{
    examAddress, name, credits, mandatory
    solarYear,
    courseAddress, courseName,
    professorName, professorSurname, professorAddress
  }> = []
}
end note
ExamsList --|> marvin.Duck
