!include ../interfaces/duck.iuml
class ManageExams{
  == types ==
  - PUSH_NEW_EXAM : string
  - SET_ALL_EXAMS_LIST : string
  - SET_EXAMS_LIST_BY_COURSE : string
  - SET_PROFESSOR_LIST : string
  == actions ==
  + pushNewExam(sting) : object
  + setAllExamsList(array<Object>) : object
  + setExamsListByCourse(array<Object>) : object
  + setProfessorList(array<Object>) : object
  + listIsLoading(): object
  + listHasErrored(): object
}

note right of ManageExams
initialState = {
  loading: false,
  errored: false,
  allExamsList: array<{name, credits, courseName, professorName, professorSurname}> = [],
  examsListByCourse: array<{name, credits, professorName, professorSurname}> = [],
  professorList: array<{name, surname, address} = []
}
end note

ManageExams --|> marvin.Duck
