!include ../interfaces/duck.iuml
class TeacherExams{
  -- types --
  - SET_EXAMS_LIST: string
  - PUSH_EXAM: string
  - POP_EXAM: string
  - LIST_LOADING: string
  - LIST_ERRORED: string
  - LIST_FINISHED: string
  -- selectors --
  + examByCode(int): array<object>
  + examByCourse(int): array<object>
  -- actions --
  + setExamsList(array<object>): object
  + pushExam(object): object
  + popExam(string): object
  + listIsLoading(): object
  + listHasErrored(): object
  + listHasFinished(): object
}
note right of TeacherExams
initialState = {
  loading: false,
  errored: false,
  list: array<{code, courseName, address, index}>
}
end note
TeacherExams --|> marvin.Duck
