@startuml

title Relationships - Class Diagram for Marvin Frontend

package Bootstrap-React <<npm module components>> {

!include bootstrap/button.iuml
!include bootstrap/checkbox.iuml
!include bootstrap/formcontrol.iuml


class FormGroup{
int v
}

class PageHeader{
int v
}

!include bootstrap/panel.iuml


class Radio{
int v
}

class Table{
int v
}

class Links?{
bootstrap links?
}

}

package custom-components <<components created by us>>{

!include custom/navbar.iuml

!include custom/footer.iuml


class Login <<UC 2>>{
  ---
  + getTypeUser()
}

class Logout <<UC 4>>{
  ---
  + resetStore()
  + resetHistory()
}

}

package HelpPage <<UC 1>> {
  class HelpPage{
    + export default function()
  }
}

package PricePage <<UC 11>> {
  class PricePage{
    + currentEthPrice()
    + currentGasPrice()
    ---
    + export default function()
  }
}

package SubmissionPage <<UC 13>> {
  class SubmissionPage{
    + currentAddr(addr)
    + courses(List[])
    ---
    + export default function()
    + submitStudent()
    + submitTeacher()
  }
}

!include university/index.iuml
!include admin/index.iuml
!include teacher/index.iuml
!include student/index.iuml


@enduml
