@startuml

title Relationships - Class Diagram for Marvin Frontend

skinparam classAttributeIconSize 0

skinparam linetype ortho

left to right direction

/' Base Bootstrap elements and Custom one '/
    !include bootstrap/index.iuml
    !include custom/index.iuml

/'Page templates or public one '/
    !include public/index.iuml

/' User pages different section for each one '/
    !include university/index.iuml
    !include admin/index.iuml
    !include teacher/index.iuml
    !include student/index.iuml

    !include routes/index.iuml

UniversityPages -[hidden]left- CustomComponents
AdminPages -[hidden]left- CustomComponents
TeacherPages -[hidden]right- CustomComponents
HelpPage -[hidden]right- CustomComponents

CustomComponents -[hidden]left-  PricePage
SubmissionPage -[hidden]left- CustomComponents

TeacherPages -[hidden]left- CustomComponents


@enduml
