@startuml

hide circle

title Relationships - Class Diagram for Marvin Frontend

skinparam classAttributeIconSize 0

skinparam linetype ortho

skinparam hide circle

left to right direction

   !include app/index.iuml

/' Base Bootstrap elements and Custom one '/
    !include bootstrap/index.iuml
    !include custom/index.iuml

/'Page templates or public one '/
    !include pageTemplates/index.iuml
    !include public/index.iuml

/' User pages different section for each one '/
    !include university/index.iuml
    !include admin/index.iuml
    !include teacher/index.iuml
    !include student/index.iuml

    !include routes/indexPac.iuml

/' Containers  '/
    !include container/container.iuml


/' layout position packages '/
    UniversityPages -[hidden]- CustomComponents
    AdminPages -[hidden]- CustomComponents
    TeacherPages -[hidden]- CustomComponents
    PublicPages -[hidden]- CustomComponents
    CustomComponents -[hidden]- BR

@enduml
