!include redux.iuml
namespace aggregators <<istantiate the custom classes to fill in the redux store>>{
  !include aggregators/sagas.iuml
  !include aggregators/reducers.iuml

  redux.SagaMiddleware  ..> Sagas : <<create>>
    Sagas *-- "1..*" marvin.Saga

  redux.Store ..> Reducers : <<create>>
  Reducers *-- "1..*" marvin.Duck
}
