@startuml
!include redux.iuml
!include react.iuml
!include reactRedux.iuml
!include aggregators.iuml
skinparam linetype ortho
namespace marvin <<business logic for the frontend app>> {
  !include interfaces/duck.iuml
  !include interfaces/saga.iuml
  !include ducks/University.iuml
  !include sagas/UniversitySaga.iuml
  '!include containers/AdminOverviewContainer.iuml

  !include ducks/Admin.iuml
  !include sagas/AdminSaga.iuml

  !include ducks/Session.iuml
  !include sagas/SessionSaga.iuml

  !include ducks/Booking.iuml
  !include sagas/BookingSaga.iuml

  !include ducks/ManageYears.iuml
  !include sagas/ManageYearsSaga.iuml
}
@enduml
