@startuml
!include redux.iuml
!include aggregators.iuml
skinparam linetype ortho
skinparam classAttributeIconSize 0
namespace marvin <<business logic for the frontend app>> {
  !include interfaces/duck.iuml
  !include interfaces/saga.iuml

  !include ducks/Metamask.iuml

  !include ducks/AdminEmployer.iuml
  !include sagas/AdminEmployerSaga.iuml

  !include ducks/Admin.iuml
  !include sagas/AdminSaga.iuml

  !include ducks/Session.iuml
  !include sagas/SessionSaga.iuml

  !include ducks/Booking.iuml
  !include sagas/BookingSaga.iuml

  !include ducks/ManageYears.iuml
  !include sagas/ManageYearsSaga.iuml

  !include ducks/TeacherExams.iuml
  !include sagas/TeacherExamsSaga.iuml

  !include ducks/Evaluator.iuml
  !include sagas/EvaluatorSaga.iuml

  !include ducks/Student.iuml
  !include sagas/StudentSaga.iuml

  !include ducks/CourseExams.iuml
  !include ducks/ExamsList.iuml
  !include ducks/TeachersList.iuml
  !include sagas/ManageExamsSaga.iuml

  !include ducks/Course.iuml
  !include sagas/CourseSaga.iuml

}
@enduml
