@startuml
!include redux.iuml
!include react.iuml
!include reactRedux.iuml
!include aggregators.iuml
namespace marvin {
  !include interfaces/duck.iuml
  !include interfaces/saga.iuml
  !include ducks/UniversityAdmin.iuml
  !include sagas/UniversitySaga.iuml
  !include containers/AdminOverviewContainer.iuml
}
@enduml
