package StudentPages <<UC 9>> {

class StudentIndex{
    --render--
        cardWithIcon to go confirm/teacher -> StudentExams
        cardWithIcon to go confirm/student -> CreditsToEnd
}
StudentIndex ..> CardWithIcon
StudentIndex ..> PageContainer

class StudentExams{
    --functions--
        + getExams(function)
    --render--
        table with list of all exams
}
StudentExams ..> PageContainer

class CreditsToEnd{
    --functions--
        +getAllCredits()
    --render--
        show all credits and credits to end with progressbar
}
CreditsToEnd ..> PageContainer

}
