package StudentPages #BEAFCA {

class StudentIndex{
    --render--
        cardWithIcon to go ExamsList -> Exams
        cardWithIcon to go OptionalExamsList -> OptionalExams
        cardWi5thIcon to go credits summary -> Summary
}
StudentIndex ..> CardWithIcon

class StudentExams{
    --props--
        getExams : function
    --render--
        table with list of all exams
}
StudentExams ..> PageTableForm

class StudentOptionalExams{
    --props--
        getOptionalExams : function
        selectExam : function
    --render--
        table with list of all optional exams
}
StudentOptionalExams ..> PageTableForm

class StudentSummary{
    --props--
        getStudentCredits : function
    --render--
        show all credits and credits to end
}
StudentSummary ..> MessageBox

}

note left of StudentPages: UC9
