package StudentPages #BEAFCA {

class StudentIndex{
    --render--
        show credits progress on the top
        cardWithIcon to go ExamsList -> Exams
        cardWithIcon to go OptionalExams -> OptionalExams
}
StudentIndex ..> CardWithIcon

class StudentExams{
    --props--
        getExams : func
        ExamsList: array(objExams)
        myAddress: string
    --render--
        table with list of all student exams
}
StudentExams ..> PageTableForm


class StudentOptionalExams{
    --props--
        getExams : function
        ExamsList: array(objExams)
        myAddress: string
        enrollToExam: func
    --render--
        table with list of all optional exams
}
StudentOptionalExams ..> PageTableForm
StudentOptionalExams ..> ModalForm


}

note left of StudentPages: UC9
