
interface Container{
  - mapStateToProps(): object
  - mapDispatchToProps(): object
  + Container(): object
}

Container ..> reactRedux.Connect: <<use>>
note right of reactRedux.Connect
  Connect react components
  to the redux store
end note

StudentOptionalExams --|> Container
StudentSummary --|> Container
StudentExams --|> Container

UniversityAdmins --|> Container
UniversityAcademicYears --|> Container

TeacherExamStudents --|> Container
TeacherExams --|> Container

AdminUsersNotConfirmed --|> Container
AdminCourses --|> Container
AdminCourseExams --|> Container
AdminUsersConfirmed --|> Container
AdminUsersNotConfirmed --|> Container

LoginPage --|> Container
SubmissionPage --|> Container
