package TeacherPages #D4E8D5 {

class TeacherIndex {
    --render--
        heroImage
        cardWithIcon to go -> TeacherExams
}
TeacherIndex ..> CardWithIcon
TeacherIndex ..> Button

class TeacherExams {
    --props--
      getMyAssignedExams: func
      assignedExams: func
      myContract: func
    --render--
    table with exams list and one
    button to see the students
    list of the selected exam
}
TeacherExams ..> PageTableForm

class TeacherExamStudents {
    --props--
      params: object
      myWeb3Address: string
      studentsOfExam: array(objStudents)
      getStudentsOfExam: func
      addGradeToStudent: func
      location: object
    --render--
    table with the students list
    of the seleted exam
}
TeacherExamStudents ..> PageTableForm
TeacherExamStudents ..> Utils
TeacherExamStudents ..> ModalForm
TeacherExamStudents ..> Form

}

note left of TeacherPages: UC8
