package AdminPages #FFBD9D {

class AdminIndex{
--render--
    heroImage
    cardWithIcon to go confirm/teacher -> AdminUsersNotConfirmed
    cardWithIcon to go confirm/student -> AdminUsersNotConfirmed

    cardWithIcon to go user/teacher -> AdminUserConfirmed
    cardWithIcon to go user/students -> AdminUserConfirmed

    cardWithIcon to go -> AdminCourses
}
AdminIndex ..> CardWithIcon

class AdminCourses{
    --props--
        getCourses: function
        addCourse: function
        validCourse: function
    --render--
        table with courses list and form to
        add a new one from specific year
}
AdminCourses ..> PageTableForm

class AdminCourseExams{
    --props--
        course: object
        getExams: function
        addExam: function
        validExam: function
        setTeacher: function
    --render--
        table with exams list from specific course
        with a form to add a new one to the current
        course
}
AdminCourseExams ..> PageTableForm

class ConfirmStudentUser{
}
ConfirmStudentUser ..> PageTableForm

class ConfirmTeacherUser{
}
ConfirmTeacherUser ..> PageTableForm

class ExamDetails{
}

class SystemUsers{
}
SystemUsers ..> PageTableForm


}

note left of AdminPages: UC5 & UC10
