package AdminPages <<UC 5 & UC7>> {

class AdminIndex{
--render--
    heroImage
    cardWithIcon to go confirm/teacher -> AdminUsersNotConfirmed
    cardWithIcon to go confirm/student -> AdminUsersNotConfirmed

    cardWithIcon to go user/teacher -> AdminUserConfirmed
    cardWithIcon to go user/students -> AdminUserConfirmed

    cardWithIcon to go -> AdminCourses
}
AdminIndex ..> CardWithIcon
AdminIndex ..> PageContainer

class AdminUsersConfirmed{
    --props--
        + userType(string)
        + getUsers(function)
        + functionDeleteUser(function)
    --render--
        table with user list and one button
        for each row to delete
}
AdminUsersConfirmed ..> PageTableForm
AdminUsersConfirmed ..> PageContainer

class AdminUsersNotConfirmed{
    --props--
        + userType(string)
        + getUsers(function)
        + functionConfirmUser(function)
        + functionDeleteUser(function)
    --render--
        table with user list and two button
        for each row to confirm or delete
}
AdminUsersNotConfirmed ..> PageTableForm
AdminUsersNotConfirmed ..> PageContainer

class AdminCourses{
    --props--
        + getCourses(function)
        + addCourse(function)
        + validCourse(function)
    --render--
        table with courses list and form to
        add a new one from specific year
}
AdminCourses ..> PageTableForm
AdminCourses ..> PageContainer

class AdminCourseExams{
    --props--
        + course(Course)
        + getExams(function)
        + addExam(function)
        + validExam(function)
    --render--
        table with exams list from specific course
        with a form to add a new one to the current
        course
}
AdminCourseExams ..> PageTableForm
AdminCourseExams ..> PageContainer

}
