skinparam package<<UC 6 & UC10  >> {
    backgroundColor #DAE8FC
}


package UniversityPages <<UC 6 & UC10>> {

class UniversityIndex {
    --render--
        heroImage
        cardWithIcon to go -> UniversityAcademicYears
        cardWithIcon to go -> UniversityAdmins
}
UniversityIndex ..> CardWithIcon

class UniversityAcademicYears {
    --props--
        getAcademicYears: function
        addAcademicYear: function
        validAcademicYear: function
        deleteAcademicYear: function
    --render--
    table with academic years list,
     one button for each row to delete
     one of them and a form to add a
     new academic years
}
UniversityAcademicYears ..> PageTableForm


class UniversityAdmins {
    --props--
        addAdmin: function
        getAdmins: function
        validAdmin: function
        deleteAdmin: function
    --render--
    table with admins list, one
    button for each row to delete
    one of them and a form to add
    a new admin
}
UniversityAdmins ..> PageTableForm


}