@startuml
namespace web3{
    !include file/Course.iuml
    !include file/Exam.iuml
    !include file/Student.iuml
    !include file/Teacher.iuml
    !include file/UniversityContractSupplier.iuml
    !include file/University.iuml
    !include file/UniversityExam.iuml
    !include file/UniversityStudent.iuml
    !include file/UniversityTeacher.iuml
    !include file/UniversityYear.iuml
    !include file/UniversityAdmin.iuml
    !include file/User.iuml
    !include file/Year.iuml

    !include file/UserData.iuml

University ..> UniversityContractSupplier : <<use>>
UniversityExam ..> UniversityContractSupplier : <<use>>
UniversityStudent ..> UniversityContractSupplier : <<use>>
UniversityTeacher ..> UniversityContractSupplier : <<use>>
UniversityYear ..> UniversityContractSupplier : <<use>>
UniversityAdmin ..> UniversityContractSupplier : <<use>>
}
@enduml
