package PublicPages #D6C544 {

  class PublicIndex {
    --render--
    describes marvin system with images, logo and text
  }

  class HelpPage {
    --render--
    show list of paragraphs and videos/images to help user
    with common problem or questions
  }

  class PricePage {
    ----
    - currentEthPrice()
    - currentGasPrice()
    --render--
    show list of actions and related price with table
  }

  class SubmissionPage {
    --props--
    currentAddr: object
    courses: object[0..*]
    submitStudent: function
    submitTeacher: function
    --render--
    show a form with name,surname
    and two selectbox to choose type of user
  }

	PublicIndex ..> MessageBox
	SubmissionPage ..> MessageBox
}

note left of PublicPages: UC1 & UC3 & UC11

