package PublicPages #D6C544 {

  class PublicIndex {
    --props--
    metamask: bool
    account: string
    --render--
    describes marvin system with images, logo and text
    with related alert messages in case users hasn't metamask or registered account
  }
	PublicIndex ..> CardWithIcon
	PublicIndex ..> AlertDismissable

  class HelpPage {
    --render--
    show list of paragraphs and videos/images to help user
    with common problem or questions
  }
  HelpPage ..> Image

  class LoginPage {
    --props--
    login: function
    --render--
    show loging process
  }
  LoginPage ..> RedirectToHome

  class Logout {
    --render--
    show logout process
  }
	Logout ..> Image

  class Price {
    ----
    - currentEthPrice()
    - currentGasPrice()
    --render--
    show list of actions and related price with table
  }
  Price ..> PriceOperationLine

  class RedirectToHome{
    --props--
    type: string
    message: string
    --render--
    redirect to home after 1 second passing in the url type and message of alert to show
  }

  class Register {
    --props--
    currentAddr: object
    courses: object[0..*]
    signUp: function
    --render--
    show a form with name,surname
    and two selectbox to choose type of user
  }
  Register ..> Form

   class Price {
           --render--
           show all the prices of
            inside Marvin
         }

   class License {
         --render--
         show license of Marvin
       }

   class NotFound {
         --render--
         not found page 404
       }

}

note left of PublicPages: UC1 & UC3 & UC11
