@startuml

class Course{
- name: bytes32
- creditsToGraduation: uint16
- year: Year
- university: UniversityAdmin
__modifiers__
onlyAdmin
__
+ Course(_name: bytes32, _creditsForGraduation: uint16, _university: University)
+@ getExamNumber(): uint
+@ getExamContractAt(uint _index): Exam
+@ getName(): bytes32
+@ getCreditsToGraduate(): uint16
+@ getSolarYear(): uint16
+ addNewExam(_name: bytes32, _credits: uint8, _obbligatoriety: bool) {onlyAdmin}
}
@enduml
