@startuml
!include Course.iuml
!include Exam.iuml
!include Migrations.iuml
!include Student.iuml
!include Teacher.iuml
!include University.iuml
!include UniversityExam.iuml
!include UniversityStudent.iuml
!include UniversityTeacher.iuml
!include UniversityYear.iuml
!include User.iuml
!include Year.iuml
@enduml