@startuml
skinparam classAttributeIconSize 0
class Student {
- course: Course
- examList: Exam [0...*]
__
confirmedStudent
byCorrectProfessor(_ofExam: uint)
notEnrolled(_index: uint)
enrolled(_index: uint)
__
+ Student(_name: bytes32, _surname: bytes32, _publicAddress: address, _course: Course)
+@ getCourseContract(): Course
+@ getExamNumber(): uint
+@ getExamContractAt(_index: uint): Exam
+@ getExamSubscriptionAt(_index: uint): bool
+@ getExamValuationAt(_index: uint): uint8
+ enrollToOptionalExam(_index: uint) {onlySubject, notEnrolled(_index: uint)}
+ registerValuation(_exam: uint, _valuation: uint8) {byCorrectProfessor(index: uint), confirmedStudent, enrolled(_index: uint)}
+ getIndexOfExam(exam: Exam): uint
}
@enduml
