@startuml

class University #99FFF3 {
#universityAddress: address
__modifiers__
onlyFounder
registrableAddress
__
+University()
+@ isUniversityFounder(_address: address): bool
+@ getRoleByAddress(_address: address): uint8
+@ login(): uint8
}
@enduml
