@startuml
skinparam classAttributeIconSize 0
class UniversityAdmin #AquaMarine {
- adminList: address [0...*]
__
validAdminAddress( _address:address)
onlyAdmin
__
+@ isAdmin(_adminAddress: address): bool
+@ getAdminNumber(): uint
+@ getAdminAt(_index: uint): address
+@ getRoleByAddress(_address: address): uint8
+ addNewAdmin(_adminAddress: address) {onlyFounder, registrableAddress(_adminAddress: address)}
+ removeAdmin(_address: address) {onlyFounder, validAdminAddress(_address: address)}
}
@enduml
