@startuml
skinparam classAttributeIconSize 0
class University{
#universityAddress: address
__
onlyFounder
registrableAddress
__
+University()
+@ isUniversityFounder(_address: address): bool
+@ getRoleByAddress(_address: address): uint8
+@ login(): uint8
}
@enduml
