@startuml
skinparam classAttributeIconSize 0
class User #LightGreen {
# publicAddress: address
# name: bytes32
# surname: bytes32
# university: University
__
onlySubject
__
+ User(_name: bytes32, _surname: bytes32, _publicAddress: address)
+@ getPublicAddress(): address
+@ getName(): bytes32
+@ getSurname(): bytes32
}
@enduml
