@startuml

class User #87FF95 {
# publicAddress: address
# name: bytes32
# surname: bytes32
# university: University
__modifiers__
onlySubject
__
+ User(_name: bytes32, _surname: bytes32, _publicAddress: address)
+@ getPublicAddress(): address
+@ getName(): bytes32
+@ getSurname(): bytes32
}
@enduml
