/'
Bootstrap components
from https://react-bootstrap.github.io/components/alerts/
'/
package Bootstrap-React <<npm module components>> {

!include button.iuml
!include checkbox.iuml
!include formcontrol.iuml
!include panel.iuml


class FormGroup{
int v
}

class PageHeader{
int v
}

class Radio{
int v
}

class Table{
int v
}

class Links?{
bootstrap links?
}

}