/'
Bootstrap components
from https://react-bootstrap.github.io/components/alerts/
'/
package Bootstrap-React <<npm module components>> {

/'BEGIN Form'/
!include formgroup.iuml
!include formcontrol.iuml
!include controllabel.iuml

!include radio.iuml
/'END Form'/

!include panel.iuml
!include table.iuml
!include button.iuml
!include progressbar.iuml
}