class Panel{
  --props--
       active : boolean
       disabled : boolean
       onClick : function
  --render--
    apply a basic border
    and padding to contain
    some content
}
/'Questa è una prova 3'/