class ProgressBar{
    --props--
        + min : number
        + now : number
        + max : number
        + label : node
        + srOnly : boolean
        + striped : boolean
        + active : boolean
}