class Radio{
  --props--
      + inline : boolean
      + disabled : boolean
      + title : string
      + validationState : StateEnum
      + inputRef()
}
Radio ..> StateEnum
/'Radio button'/