interface Duck{
  + initialState(): object
  + reducer(object, object): object
  -- purpouse --
  classes inherited by this interface
  are responsible to manage the redux
  state by reacting to predefined actions
}
