interface Saga{
  + void handler()
  -- purpouse --
  classes inherited by this interface achieve
  asyncronus connection with external apis
  and notify the retrived data to the app
  via ducks' actions
}
note bottom of Saga
 Strategy Pattern
end note
