class PageContainer {
    --props--
        children: nodes
        route: object
        location: object
    --render--
        render the navbar and the footer
}

PageContainer ..> Panel
PageContainer ..> Footer
PageContainer ..> Navbar
PageContainer ..> ErrorTaker
PageContainer ..> AlertDismissable
PageContainer ..> LoadingSpinner
Page ..> PageContainer

