class PageContainer {
    --props--
        loggedIn: bool
        links: object[0...*]
        children: nodes
    --render--
        render the navbar and the footer
}

PageContainer ..> Panel
PageContainer ..> Footer
PageContainer ..> Navbar
Page ..> PageContainer

