class PageTableForm{
    --props--
        getTableData: function
        tableData: array(dataObj)
        headerInfo: array(strings)
        tableButtons: array(buttons)
        columFilter: bool
    --render--
        render table with custom row with buttons
}
PageTableForm ..> Table
PageTableForm ..> TemplateButton
PageTableForm ..> Utils