class Reducers{
  + {static} combine(): object
}
note right of Reducers
{
  academicYears: ManageYears,
  accounts: Admin,
  admins: AdminEmployer,
  course: CourseExams,
  courses: Course,
  currentUser: Session
  exams: ExamsList,
  metamask: Metamask,
  selectedExam: Evaluator,
  signup: Booking,
  studentData: Student,
  teacherData: TeacherExams,
  techersList: TeachersList
}
end note
