class Reducers{
  + {static} combine(): object
}
note right of Reducers
{
  academicYears: ManageYears,
  accounts: Admin,
  admins: AdminEmployer,
  courses: Course,
  currentUser: Session
  exams: ManageExams,
  metamask: Metamask,
  selectedExam: Evaluator,
  signup: Booking,
  studentData: Student,
  teacherData: TeacherExams
}
end note
