@startuml

box "React" #Pink
participant Virtual_DOM
participant UniversityAdmins
end box

box "Redux" #Plum
participant Store
participant AdminEmployer
participant AdminEmployerSaga
end box

box "Web3" #LightGreen
participant UniversityAdmin
end box

[o-> UniversityAdmins: "Add Admin"
note left: A university user clicks "Add Admin"\non "Manage admins" page
activate UniversityAdmins

UniversityAdmins -> AdminEmployerSaga: addAdmin()
activate AdminEmployerSaga

AdminEmployerSaga -> UniversityAdmin: addNewAdmin()
activate UniversityAdmin


alt  web3 writes on the blockchain
    AdminEmployerSaga -> AdminEmployer: pushAdmin(string)
    activate AdminEmployer

    AdminEmployer --> Store: reducer
    activate Store
    deactivate Store


else  web3 doesn't writes on the blockchain
    UniversityAdmin --> AdminEmployerSaga: errored()
    deactivate UniversityAdmin

    AdminEmployerSaga --> AdminEmployer: errored()
    deactivate AdminEmployer

end

deactivate AdminEmployerSaga



alt errored = true
    UniversityAdmins -> UniversityAdmins: render()
    activate UniversityAdmins

    UniversityAdmins --> Virtual_DOM: update
    note left: show a error message
    deactivate UniversityAdmins

else errored = false
    UniversityAdmins -> UniversityAdmins: render()
    activate UniversityAdmins

    UniversityAdmins --> Virtual_DOM: update
    note left: show a confirm message
    deactivate UniversityAdmins
end

deactivate UniversityAdmins

@enduml