@startuml

box "React" #Pink
participant Virtual_DOM
participant TeacherExams
end box

box "Redux" #Plum
participant Store
participant TeacherExam
participant TeacherExamsSaga
end box

box "Web3" #LightGreen
participant Teacher
end box

[o-> TeacherExams: "Manage Exams"
note left: A teacher clicks "Manage Exams"\non his home page
activate TeacherExams

TeacherExams -> TeacherExamsSaga: getExams()
activate TeacherExamsSaga
note right: STATE -> loading = true

loop for each exam held by the teacher
TeacherExamsSaga -> Teacher: getListAction()
activate Teacher
    alt exam fetched
        Teacher -> TeacherExamsSaga: object
        TeacherExamsSaga -> TeacherExam : setExamsList()
        activate TeacherExam
        TeacherExam --> Store: reducer
        deactivate TeacherExam

        activate Store
        deactivate Store
    else exam not fetched
        Teacher -> TeacherExamsSaga: errored()
        TeacherExamsSaga -> TeacherExam : ListHasErrored()
        activate TeacherExam
        deactivate TeacherExam
        note right: STATE -> loading = false

    end
    deactivate Teacher
    deactivate TeacherExamsSaga
end

TeacherExams -> TeacherExams: render()
activate TeacherExams

TeacherExams --> Virtual_DOM: update
note left: Show a loading component
deactivate TeacherExams

TeacherExams -> TeacherExams: render()
activate TeacherExams

TeacherExams --> Virtual_DOM: update
note left: Show the list


deactivate TeacherExams


@enduml