@startuml

hide circle

skinparam classAttributeIconSize 0

skinparam linetype ortho

skinparam hide circle



/'
Custom components
created by 353 group
'/

package custom-components as CustomComponents {

!include alertDismissable.iuml

!include errorTaker.iuml

!include loadingSpinner.iuml

!include modalForm.iuml

!include priceOperationLine.iuml

!include templateButton.iuml

!include navbar.iuml

!include field.iuml

!include form.iuml

!include footer.iuml

!include cardWithIcon.iuml

!include messageBox.iuml

}

@enduml
