
class AppRouting <<I'm the Father of all components>>{
    Factory to create Router
    and the pageContainer where every page with navbar and footer will be born
    --props--
        + userType(string)
}


AppRouting ..> Routes

AppRouting ..> Router
AppRouting ..> PageContainer

class Router <<created by react-router>>{

}

note top of AppRouting
        React App from here!!
    end note
