class CardWithIcon{
    --props--
        title: string
        icon: string
        link: string
    --render--
        card with icon and description
        plus a link button to go to a specific page
}
CardWithIcon ..> Image