class Field{
    --props--
        name(str)
        type(str)
        values(array json?)
        validateFunction(function)
    ----
        - changeState()
    --render--
        display the type of the field and
        dynamic update its value and state
}