class Field{
    --props--
        id(int)
        name(str)
        label(string)
        help(string)
        type(string)
        values(array json?)
        validateFunction(function)
    ----
        - changeState()
    --render--
        display the type of the field and
        dynamic update its value and state
}
Field ..|> ControlLabel
Field ..|> FormControl
Field ..|> FormGroup