class Field{
    --props--
        id: number
        name: string
        label: string
        help: string
        type: string
        values: object
        validateFunction: function
    ----
        - changeState()
    --render--
        display the type of the field and
        dynamic update its value and state
}
Field ..> ControlLabel
Field ..> FormControl
Field ..> FormGroup
Field ..> Radio
Field ..> MenuItem
Field ..> TemplateButton