/'
Custom components
created by 353 group
'/

package custom-components as CustomComponents <<components created by us>>{

!include navbar.iuml

!include field.iuml

!include form.iuml

!include footer.iuml

!include login.iuml

!include logout.iuml

!include cardWithIcon.iuml

!include deleteButton.iuml

!include messageBox.iuml

!include pageTableForm.iuml

!include pageContainer.iuml

}

Page ..> PageContainer
