/'
Custom components
created by 353 group
'/

package Custom-Components as CustomComponents {

!include utils.iuml

!include fieldtypes.iuml

!include alertDismissable.iuml

!include errorTaker.iuml

!include loadingSpinner.iuml

!include modalForm.iuml

!include priceOperationLine.iuml

!include templateButton.iuml

!include navbar.iuml

!include field.iuml

!include form.iuml

!include footer.iuml

!include cardWithIcon.iuml

!include messageBox.iuml

}

note bottom of CustomComponents: components created by us

