/'
Custom components
created by 353 group
'/

package Custom-Components as CustomComponents {

!include navbar.iuml

!include field.iuml

!include form.iuml

!include footer.iuml

!include cardWithIcon.iuml

!include deleteButton.iuml

!include messageBox.iuml

}

note bottom of CustomComponents: components created by us

