class Message {
    --props--
       isError: boolean
       description: string
	   isWaiting: boolean
    --render--
    modal with positive or failure icon with description
}

Message ..> Modal
Message ..> Button
