
class ModalForm{
    --props--
       title: string
       show: bool
	   children: node
	   yesFunction: func
	   noFunction: func
	   keyForModal: objKey
    --render--
    modal a modal with props to show and display yes and no button with related event clicks, inside anything you want
}