class Navbar{
  --props--
    loggedIn: boolean
    links: object[0..*]
  --render--
    list of link-logo to index
    link to price page
    link to help page
    links based on login and type user
}

