class PageContainer{
    Base Component for all the routes
    --props--
        + isLoading(bool)
        + children(nodes)
    --render--
        render the whole content of the page in a panel
         It shows a progressbar or spinner when the data of the page is loading
         At the bottom it renders the footer too
}
PageContainer ..> Panel
PageContainer ..> Footer
PageContainer ..> ProgressBar
