
class RouterFactory <<I'm the Father of all components>>{
    Factory to create Router with right routes and related navbar
    and inside me the pageContainer where every page will be born
    --props--
        + userType(string)
    --render--
        render the right navbar
}


RouterFactory ..> Routes

RouterFactory ..> Navbar
RouterFactory ..> Router
RouterFactory ..> PageContainer

class Router <<created by react-router>>{

}

note top of RouterFactory
        React App from here!!
    end note