react.LoginPage ..> redux.SessionSaga
react.SubmissionPage ..> redux.BookingSaga

react.AdminCourseExams ..> redux.ManageExamsSaga
react.AdminUsersConfirmed ..> redux.AdminSaga
react.AdminUsersNotConfirmed ..> redux.AdminSaga
react.AdminCourses ..> redux.CourseSaga

react.StudentSummary ..> redux.StudentSaga
react.StudentOptionalExam ..> redux.StudentSaga
react.StudentExams ..> redux.StudentSaga

react.UniversityAdmins ..> redux.AdminEmployerSaga
react.UniversityAcademicYears ..> redux.ManageYearsSaga

react.TeacherExamStudents ..> redux.EvaluatorSaga
react.TeacherExams ..> redux.TeacherExamsSaga
