redux.SessionSaga ..> web3.Session
'getData, getRole'


redux.BookingSaga ..> web3.Session
'create'
''''''''''''''''''
redux.BookingSaga ..> web3.Year
'getAcademicYearContractByYear
redux.BookingSaga ..> web3.UniversityYear
'getCourseNumber, getCourseContractAt
redux.BookingSaga ..> web3.Course
'getName

redux.AdminEmployerSaga ..> web3.UniversityAdmin
'getAdminNumber, getAdminAt, addAdmin, removeAdmin'

redux.AdminSaga ..> web3.UniversityStudent
'getStudent*, getNonApprovedStudent*'
redux.AdminSaga ..> web3.UniversityTeacher
'getTeacher*, getNonApprovedTeacher*'
redux.AdminSaga ..> web3.User

redux.ManageYearsSaga ..> web3.UniversityYear
'getAcademicYerNumber, getAcademicYearContractAt,''
''''''''''''''''''''addAdmin, removeAdmin
redux.ManageYearsSaga ..> web3.Year
'getSolarYear'

redux.EvaluatorSaga ..> web3.Exam
'getEnrolled*'
redux.EvaluatorSaga ..> web3.User
'getName, getSurname'
'''''''''''''
redux.EvaluatorSaga ..> web3.Teacher
'registerNewVoteStudentExam'

redux.TeacherExamsSaga ..> web3.Teacher
'getExam*'
redux.TeacherExamsSaga ..> web3.Exam
'getName, getCourse'
redux.TeacherExamsSaga ..> web3.Course
'getName'

redux.CourseSaga ..>web3.Year
'addNewCourse, getSolarYear'
redux.CourseSaga ..>web3.Course
'getName, getSolarYear'

redux.ManageExamsSaga ..>web3.Course
'addNewExam, getName, getExamContractAt'
redux.ManageExamsSaga ..>web3.Exam
'getName, getCredits, getTeacherContract'
redux.ManageExamsSaga ..>web3.Teacher
'getName, getSurname, getAddress'
redux.ManageExamsSaga ..>web3.UniversityExam
'associateTeacherToExam'

redux.ManageYearsSaga ..>web3.UniversityYear
'addNewYear, removeAcademicYear, getAcademicYear*'
